[book]
authors = ["lzzsG"]
language = "en"
multilingual = false
src = "src"
title = "os-lectures-mdbook"


[output.html]
default-theme = "light"
preferred-dark-theme = "black"
git-repository-url = "https://github.com/LearningOS/os-lectures-mdbook"
git-repository-icon = "fa-github"


[output.html.playground]
editable = true
